"""Review-feedback logging and inspectable confidence calibration."""

from __future__ import annotations

import json
import os
from collections.abc import Sequence
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from .contracts import LabelPrediction

CALIBRATION_FEATURES = (
    "top_similarity",
    "margin",
    "prompt_top_similarity",
    "prompt_margin",
    "panns_support_score",
    "panns_contradiction_score",
    "radius_ratio",
    "label_example_count_log",
    "label_prototype_count",
    "structure_agreement",
    "broad_family_agreement",
    "out_of_distribution",
    "duplicate_conflict",
)
VALID_CALIBRATION_OUTCOMES = frozenset({"prediction_correct", "parent_family_correct"})


@dataclass(frozen=True)
class ReviewFeedback:
    file_sha256: str
    provider_id: str
    predicted_label: str
    accepted: bool
    top_similarity: float
    margin: float
    radius_ratio: float
    label_example_count: int
    label_prototype_count: int
    structure_agreement: float
    created_utc: str
    final_approved_label: str = ""
    parent_family_accepted: bool = False
    prompt_top_similarity: float = 0.0
    prompt_margin: float = 0.0
    panns_support_score: float = 0.0
    panns_contradiction_score: float = 0.0
    broad_family_agreement: float = 0.5
    out_of_distribution: float = 0.0
    duplicate_conflict: float = 0.0
    brain_version: str = ""
    taxonomy_version: str = ""

    @classmethod
    def from_prediction(
        cls,
        file_sha256: str,
        prediction: LabelPrediction,
        *,
        accepted: bool,
        structure_agreement: float = 0.5,
    ) -> ReviewFeedback:
        return cls(
            file_sha256=file_sha256,
            provider_id=prediction.provider_id,
            predicted_label=prediction.predicted_label,
            accepted=bool(accepted),
            top_similarity=float(prediction.top_similarity),
            margin=float(prediction.margin),
            radius_ratio=float(prediction.radius_ratio),
            label_example_count=int(prediction.evidence.get("label_example_count", 0)),
            label_prototype_count=int(prediction.evidence.get("label_prototype_count", 0)),
            structure_agreement=float(structure_agreement),
            created_utc=datetime.now(timezone.utc).isoformat(),
            final_approved_label=prediction.predicted_label if accepted else "",
            parent_family_accepted=bool(accepted),
        )


class ReviewFeedbackStore:
    """Append-only JSONL evidence generated by human review decisions."""

    def __init__(self, path: Path) -> None:
        self.path = Path(path)

    def append(self, feedback: ReviewFeedback) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        line = json.dumps(asdict(feedback), sort_keys=True) + "\n"
        with self.path.open("a", encoding="utf-8") as handle:
            handle.write(line)
            handle.flush()
            os.fsync(handle.fileno())

    def read_all(self) -> tuple[ReviewFeedback, ...]:
        if not self.path.exists():
            return ()
        rows: list[ReviewFeedback] = []
        for line in self.path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            payload = json.loads(line)
            rows.append(ReviewFeedback(**payload))
        return tuple(rows)


def feedback_features(row: ReviewFeedback) -> np.ndarray:
    return np.asarray(
        [
            row.top_similarity,
            row.margin,
            row.prompt_top_similarity,
            row.prompt_margin,
            row.panns_support_score,
            row.panns_contradiction_score,
            row.radius_ratio,
            float(np.log1p(row.label_example_count)),
            float(row.label_prototype_count),
            row.structure_agreement,
            row.broad_family_agreement,
            row.out_of_distribution,
            row.duplicate_conflict,
        ],
        dtype=np.float64,
    )


class ConfidenceCalibrator:
    """Small probability model fitted only when enough reviewed outcomes exist."""

    def __init__(self) -> None:
        self.model = None
        self.numpy_mean: np.ndarray | None = None
        self.numpy_scale: np.ndarray | None = None
        self.numpy_weights: np.ndarray | None = None
        self.method = "unfitted"
        self.outcome = "prediction_correct"

    def fit(
        self,
        feedback: Sequence[ReviewFeedback],
        *,
        outcome: str = "prediction_correct",
    ) -> None:
        """Fit one interpretable outcome from reviewed evidence.

        Args:
            feedback: Non-leaking, hash-deduplicated reviewed events.
            outcome: ``prediction_correct`` or ``parent_family_correct``.

        Raises:
            ValueError: If the outcome is unsupported or lacks enough positive
                and negative reviewed examples.

        Side Effects:
            Imports scikit-learn when available; otherwise uses NumPy.
        """
        if outcome not in VALID_CALIBRATION_OUTCOMES:
            raise ValueError(f"unsupported calibration outcome: {outcome}")
        if len(feedback) < 20:
            raise ValueError("at least 20 reviewed decisions are required for calibration")
        self.outcome = outcome
        y = np.asarray([1 if _feedback_outcome(row, outcome) else 0 for row in feedback], dtype=np.int32)
        if len(set(y.tolist())) < 2:
            raise ValueError("calibration requires both accepted and rejected outcomes")
        x = np.vstack([feedback_features(row) for row in feedback])
        try:
            from sklearn.linear_model import LogisticRegression
            from sklearn.pipeline import make_pipeline
            from sklearn.preprocessing import StandardScaler
        except ImportError:
            self._fit_numpy_logistic(x, y)
            return
        model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000, class_weight="balanced"))
        model.fit(x, y)
        self.model = model
        scaler = model.named_steps["standardscaler"]
        logistic = model.named_steps["logisticregression"]
        self.numpy_mean = np.asarray(scaler.mean_, dtype=np.float64)
        self.numpy_scale = np.asarray(scaler.scale_, dtype=np.float64)
        self.numpy_weights = np.concatenate(
            (
                np.asarray(logistic.intercept_, dtype=np.float64),
                np.asarray(logistic.coef_[0], dtype=np.float64),
            )
        )
        self.method = "logistic"

    def predict_probability(self, row: ReviewFeedback) -> float | None:
        if self.model is not None:
            return float(self.model.predict_proba(feedback_features(row).reshape(1, -1))[0, 1])
        if self.numpy_mean is None or self.numpy_scale is None or self.numpy_weights is None:
            return None
        features = (feedback_features(row) - self.numpy_mean) / self.numpy_scale
        design_row = np.concatenate((np.ones(1, dtype=np.float64), features))
        logit = float(np.clip(design_row @ self.numpy_weights, -35.0, 35.0))
        return float(1.0 / (1.0 + np.exp(-logit)))

    def save(self, path: Path, *, metadata: dict[str, object] | None = None) -> None:
        """Save an inspectable, dependency-free calibrator artifact."""
        if self.numpy_mean is None or self.numpy_scale is None or self.numpy_weights is None:
            raise ValueError("cannot save an unfitted confidence calibrator")
        payload = {
            "schema_version": 1,
            "method": self.method,
            "outcome": self.outcome,
            "feature_names": list(CALIBRATION_FEATURES),
            "feature_mean": self.numpy_mean.tolist(),
            "feature_scale": self.numpy_scale.tolist(),
            "weights_with_intercept": self.numpy_weights.tolist(),
            "metadata": dict(metadata or {}),
        }
        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    @classmethod
    def load(cls, path: Path) -> ConfidenceCalibrator:
        """Load a saved calibrator without importing scikit-learn."""
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        if tuple(payload.get("feature_names", [])) != CALIBRATION_FEATURES:
            raise ValueError("calibration feature contract does not match this runtime")
        calibrator = cls()
        calibrator.numpy_mean = np.asarray(payload["feature_mean"], dtype=np.float64)
        calibrator.numpy_scale = np.asarray(payload["feature_scale"], dtype=np.float64)
        calibrator.numpy_weights = np.asarray(payload["weights_with_intercept"], dtype=np.float64)
        if calibrator.numpy_mean.shape != (len(CALIBRATION_FEATURES),):
            raise ValueError("invalid calibration feature mean shape")
        if calibrator.numpy_scale.shape != calibrator.numpy_mean.shape:
            raise ValueError("invalid calibration feature scale shape")
        if calibrator.numpy_weights.shape != (len(CALIBRATION_FEATURES) + 1,):
            raise ValueError("invalid calibration weight shape")
        calibrator.method = f"loaded_{payload.get('method', 'unknown')}"
        calibrator.outcome = str(payload.get("outcome", "prediction_correct"))
        if calibrator.outcome not in VALID_CALIBRATION_OUTCOMES:
            raise ValueError(f"unsupported saved calibration outcome: {calibrator.outcome}")
        return calibrator

    def _fit_numpy_logistic(self, features: np.ndarray, outcomes: np.ndarray) -> None:
        """Fit a deterministic NumPy fallback when scikit-learn is unavailable."""
        mean = features.mean(axis=0)
        scale = features.std(axis=0)
        scale = np.where(scale > 1e-12, scale, 1.0)
        standardized = (features - mean) / scale
        design = np.column_stack((np.ones(len(standardized), dtype=np.float64), standardized))
        weights = np.zeros(design.shape[1], dtype=np.float64)
        targets = outcomes.astype(np.float64)
        learning_rate = 0.08
        regularization = 1e-3
        for _ in range(2000):
            logits = np.clip(design @ weights, -35.0, 35.0)
            probabilities = 1.0 / (1.0 + np.exp(-logits))
            gradient = design.T @ (probabilities - targets) / len(targets)
            gradient[1:] += regularization * weights[1:]
            weights -= learning_rate * gradient
        self.model = None
        self.numpy_mean = mean
        self.numpy_scale = scale
        self.numpy_weights = weights
        self.method = "numpy_logistic"


@dataclass(frozen=True)
class CalibrationProbabilities:
    """Human-readable confidence outputs from separated calibration targets."""

    prediction_correct: float | None
    parent_family_correct: float | None
    review_required: float | None


class ConfidenceCalibrationBundle:
    """Optional prediction and parent-family calibrators for production use."""

    def __init__(
        self,
        prediction_calibrator: ConfidenceCalibrator,
        parent_family_calibrator: ConfidenceCalibrator | None = None,
    ) -> None:
        self.prediction_calibrator = prediction_calibrator
        self.parent_family_calibrator = parent_family_calibrator

    @classmethod
    def load(cls, directory: Path) -> ConfidenceCalibrationBundle:
        """Load available dependency-free calibration artifacts."""
        root = Path(directory)
        prediction = ConfidenceCalibrator.load(root / "confidence_calibrator.json")
        parent_path = root / "parent_family_calibrator.json"
        parent = ConfidenceCalibrator.load(parent_path) if parent_path.is_file() else None
        return cls(prediction, parent)

    def predict(self, feedback: ReviewFeedback) -> CalibrationProbabilities:
        """Return correct-label, correct-parent, and Review probabilities."""
        prediction_correct = self.prediction_calibrator.predict_probability(feedback)
        parent_correct = (
            self.parent_family_calibrator.predict_probability(feedback)
            if self.parent_family_calibrator is not None
            else None
        )
        review_required = None if prediction_correct is None else 1.0 - prediction_correct
        return CalibrationProbabilities(prediction_correct, parent_correct, review_required)


def _feedback_outcome(row: ReviewFeedback, outcome: str) -> bool:
    if outcome == "prediction_correct":
        return bool(row.accepted)
    if outcome == "parent_family_correct":
        return bool(row.parent_family_accepted)
    raise ValueError(f"unsupported calibration outcome: {outcome}")
