"""Review-feedback logging and inspectable confidence calibration."""

from __future__ import annotations

import json
import os
from collections.abc import Sequence
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from .contracts import LabelPrediction

CALIBRATION_FEATURES = (
    "top_similarity",
    "margin",
    "radius_ratio",
    "label_example_count_log",
    "label_prototype_count",
    "structure_agreement",
)


@dataclass(frozen=True)
class ReviewFeedback:
    file_sha256: str
    provider_id: str
    predicted_label: str
    accepted: bool
    top_similarity: float
    margin: float
    radius_ratio: float
    label_example_count: int
    label_prototype_count: int
    structure_agreement: float
    created_utc: str

    @classmethod
    def from_prediction(
        cls,
        file_sha256: str,
        prediction: LabelPrediction,
        *,
        accepted: bool,
        structure_agreement: float = 0.5,
    ) -> ReviewFeedback:
        return cls(
            file_sha256=file_sha256,
            provider_id=prediction.provider_id,
            predicted_label=prediction.predicted_label,
            accepted=bool(accepted),
            top_similarity=float(prediction.top_similarity),
            margin=float(prediction.margin),
            radius_ratio=float(prediction.radius_ratio),
            label_example_count=int(prediction.evidence.get("label_example_count", 0)),
            label_prototype_count=int(prediction.evidence.get("label_prototype_count", 0)),
            structure_agreement=float(structure_agreement),
            created_utc=datetime.now(timezone.utc).isoformat(),
        )


class ReviewFeedbackStore:
    """Append-only JSONL evidence generated by human review decisions."""

    def __init__(self, path: Path) -> None:
        self.path = Path(path)

    def append(self, feedback: ReviewFeedback) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        line = json.dumps(asdict(feedback), sort_keys=True) + "\n"
        with self.path.open("a", encoding="utf-8") as handle:
            handle.write(line)
            handle.flush()
            os.fsync(handle.fileno())

    def read_all(self) -> tuple[ReviewFeedback, ...]:
        if not self.path.exists():
            return ()
        rows: list[ReviewFeedback] = []
        for line in self.path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            payload = json.loads(line)
            rows.append(ReviewFeedback(**payload))
        return tuple(rows)


def feedback_features(row: ReviewFeedback) -> np.ndarray:
    return np.asarray(
        [
            row.top_similarity,
            row.margin,
            row.radius_ratio,
            float(np.log1p(row.label_example_count)),
            float(row.label_prototype_count),
            row.structure_agreement,
        ],
        dtype=np.float64,
    )


class ConfidenceCalibrator:
    """Small probability model fitted only when enough reviewed outcomes exist."""

    def __init__(self) -> None:
        self.model = None
        self.method = "unfitted"

    def fit(self, feedback: Sequence[ReviewFeedback]) -> None:
        if len(feedback) < 20:
            raise ValueError("at least 20 reviewed decisions are required for calibration")
        y = np.asarray([1 if row.accepted else 0 for row in feedback], dtype=np.int32)
        if len(set(y.tolist())) < 2:
            raise ValueError("calibration requires both accepted and rejected outcomes")
        x = np.vstack([feedback_features(row) for row in feedback])
        try:
            from sklearn.linear_model import LogisticRegression
            from sklearn.pipeline import make_pipeline
            from sklearn.preprocessing import StandardScaler
        except ImportError as exc:
            raise RuntimeError("confidence calibration requires scikit-learn") from exc
        model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000, class_weight="balanced"))
        model.fit(x, y)
        self.model = model
        self.method = "logistic"

    def predict_probability(self, row: ReviewFeedback) -> float | None:
        if self.model is None:
            return None
        return float(self.model.predict_proba(feedback_features(row).reshape(1, -1))[0, 1])
